version: '3.8'

services:
  pm-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pm-bot
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./logs:/app/logs
      - ./.env:/app/.env
    restart: unless-stopped
    command: ["python3", "main.py", "--skip-validation"]
    environment:
      - PYTHONUNBUFFERED=1
      - MCP_SERVER_URL=http://mcp-atlassian:9000
    depends_on:
      - mcp-atlassian
    networks:
      - pm-bot-network
  mcp-atlassian:
    image: ghcr.io/sooperset/mcp-atlassian:latest
    container_name: mcp-atlassian
    ports:
      - "9000:9000"
    environment:
      - JIRA_URL=${JIRA_SERVER}
      - JIRA_USERNAME=${JIRA_USERNAME}
      - JIRA_API_TOKEN=${JIRA_API_TOKEN}
      - CONFLUENCE_URL=${CONFLUENCE_URL}
      - LOG_LEVEL=${MCP_LOG_LEVEL:-INFO}
    command: ["--transport", "streamable-http", "--port", "9000", "-vv"]
    networks:
      - pm-bot-network
    restart: unless-stopped

networks:
  pm-bot-network:
    driver: bridge

volumes:
  pm-bot-logs:
    driver: local
  # Uncomment if using Redis
  # redis_data:
  logs: 